// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmstmxjnnshlkibtxbzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtc3RteGpubnNobGtpYnR4Ynp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDYwNjQsImV4cCI6MjA2NTU4MjA2NH0.bOICVERNDoGv1zX2EPptmKexfyYO8hf1Whm1EOlM3TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);